version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      no_cache: false
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      no_cache: false
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      no_cache: false
    restart: always
    env_file:
      - .env
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

  pong:
    container_name: pong
    build:
      context: ./requirements/bonus/pong
      dockerfile: Dockerfile
      no_cache: false
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - bonus_data:/app
    networks:
      - network

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${WORDPRESS_FOLDER}
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${MYSQL_FOLDER}
      o: bind
  bonus_data:
    driver: local
    driver_opts:
      type: none
      device: ${BONUS_FOLDER}
      o: bind

networks:
  network:
    driver: bridge